// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wallee.Data;

#nullable disable

namespace Wallee.Migrations;

[DbContext(typeof(WalleeDbContext))]
[Migration("20260529185335_AddExpectedTransaction")]
partial class AddExpectedTransaction
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.25");

        modelBuilder.Entity("Wallee.Models.Category", b =>
        {
            b.Property<int>("ID")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<bool>("Active")
                .HasColumnType("INTEGER");

            b.Property<string>("CategoryName")
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnType("TEXT");

            b.HasKey("ID");

            b.ToTable("Categories");
        });

        modelBuilder.Entity("Wallee.Models.ExpectedTransaction", b =>
        {
            b.Property<int>("ID")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Amount")
                .HasColumnType("INTEGER");

            b.Property<int?>("CategoryID")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .HasColumnType("TEXT");

            b.Property<DateTime>("ExpectedDate")
                .HasColumnType("TEXT");

            b.Property<int?>("LinkedTransactionID")
                .HasColumnType("INTEGER");

            b.Property<string>("Recurrence")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int?>("RecurrenceDay")
                .HasColumnType("INTEGER");

            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<string>("Type")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int>("WalletID")
                .HasColumnType("INTEGER");

            b.HasKey("ID");

            b.HasIndex("CategoryID");

            b.HasIndex("LinkedTransactionID");

            b.HasIndex("WalletID");

            b.ToTable("ExpectedTransactions");
        });

        modelBuilder.Entity("Wallee.Models.Transaction", b =>
        {
            b.Property<int>("ID")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Amount")
                .HasColumnType("INTEGER");

            b.Property<int?>("CategoryID")
                .HasColumnType("INTEGER");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("TEXT");

            b.Property<DateTime>("Date")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .HasColumnType("TEXT");

            b.Property<string>("Type")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int>("WalletID")
                .HasColumnType("INTEGER");

            b.HasKey("ID");

            b.HasIndex("CategoryID");

            b.HasIndex("WalletID");

            b.ToTable("Transactions");
        });

        modelBuilder.Entity("Wallee.Models.Wallet", b =>
        {
            b.Property<int>("ID")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<bool>("Active")
                .HasColumnType("INTEGER");

            b.Property<int>("Balance")
                .HasColumnType("INTEGER");

            b.Property<string>("Description")
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.HasKey("ID");

            b.ToTable("Wallets");
        });

        modelBuilder.Entity("Wallee.Models.ExpectedTransaction", b =>
        {
            b.HasOne("Wallee.Models.Category", "Category")
                .WithMany()
                .HasForeignKey("CategoryID")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("Wallee.Models.Transaction", "LinkedTransaction")
                .WithMany()
                .HasForeignKey("LinkedTransactionID")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("Wallee.Models.Wallet", "Wallet")
                .WithMany()
                .HasForeignKey("WalletID")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Category");

            b.Navigation("LinkedTransaction");

            b.Navigation("Wallet");
        });

        modelBuilder.Entity("Wallee.Models.Transaction", b =>
        {
            b.HasOne("Wallee.Models.Category", "Category")
                .WithMany("Transactions")
                .HasForeignKey("CategoryID")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("Wallee.Models.Wallet", "Wallet")
                .WithMany("Transactions")
                .HasForeignKey("WalletID")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Category");

            b.Navigation("Wallet");
        });

        modelBuilder.Entity("Wallee.Models.Category", b =>
        {
            b.Navigation("Transactions");
        });

        modelBuilder.Entity("Wallee.Models.Wallet", b =>
        {
            b.Navigation("Transactions");
        });
#pragma warning restore 612, 618
    }
}
